import { Prisma } from "@prisma/client";

export const defaultUserSelect = Prisma.validator<Prisma.userSelect>()({
  id: true,
  role: true,
  email: true,
  details: {
    select: {
      _count: {
        select: {
          offer: true,
        },
      },
      studentRecord: {
        select: {
          name: true,
          usn: true,
          branch: true,
          gender: true,
          email: true,
          image: true,
          opted: true,
          validated: true,
          resume: true,
          phoneNumber: true,
          parentsPhoneNumber: true,
          PermanentAddress: true,
          currentAddress: true,
          pinCode: true,
          bloodGroup: true,
          panCardNumber: true,
          voterId: true,
          adharCard: true,
          passportNumber: true,

          sslcboard: true,
          sslcscoreType: true,
          sslcscore: true,
          sslcmarksSheet: true,

          pucboard: true,
          pucscoreType: true,
          pucscore: true,
          pucmarksSheet: true,

          diplomaSems1score: true,
          diplomaSems1MarksSheet: true,
          diplomaSems2score: true,
          diplomaSems2MarksSheet: true,
          diplomaSems3score: true,
          diplomaSems3MarksSheet: true,
          diplomaSems4score: true,
          diplomaSems4MarksSheet: true,
          diplomaSems5score: true,
          diplomaSems5MarksSheet: true,
          diplomaSems6score: true,
          diplomaSems6MarksSheet: true,

          graduationSem1score: true,
          graduationSem1MarksSheet: true,
          graduationSem2score: true,
          graduationSem2MarksSheet: true,
          graduationSem3score: true,
          graduationSem3MarksSheet: true,
          graduationSem4score: true,
          graduationSem4MarksSheet: true,
          graduationSem5score: true,
          graduationSem5MarksSheet: true,
          graduationSem6score: true,
          graduationSem6MarksSheet: true,
          graduationSem7score: true,
          graduationSem7MarksSheet: true,
          graduationSem8score: true,
          graduationSem8MarksSheet: true,
        },
      },
    },
  },
});
